#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD605848ED7E69871 (ueno@gnu.org)
#
Name     : ibus-skk
Version  : 1.4.3
Release  : 2
URL      : https://github.com/ueno/ibus-skk/releases/download/ibus-skk-1.4.3/ibus-skk-1.4.3.tar.xz
Source0  : https://github.com/ueno/ibus-skk/releases/download/ibus-skk-1.4.3/ibus-skk-1.4.3.tar.xz
Source1 : https://github.com/ueno/ibus-skk/releases/download/ibus-skk-1.4.3/ibus-skk-1.4.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: ibus-skk-data = %{version}-%{release}
Requires: ibus-skk-libexec = %{version}-%{release}
Requires: ibus-skk-license = %{version}-%{release}
Requires: ibus-skk-locales = %{version}-%{release}
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(libskk)
BuildRequires : util-linux

%description
ibus-skk -- a Japanese SKK input engine for IBus
* What's this?
ibus-skk is an implementation of the SKK (Simple Kana-Kanji) input
method on the IBus input method framework.  Note that SKK works quite
differently from other Japanese input methods.  To learn about SKK,
see:

%package data
Summary: data components for the ibus-skk package.
Group: Data

%description data
data components for the ibus-skk package.


%package libexec
Summary: libexec components for the ibus-skk package.
Group: Default
Requires: ibus-skk-license = %{version}-%{release}

%description libexec
libexec components for the ibus-skk package.


%package license
Summary: license components for the ibus-skk package.
Group: Default

%description license
license components for the ibus-skk package.


%package locales
Summary: locales components for the ibus-skk package.
Group: Default

%description locales
locales components for the ibus-skk package.


%prep
%setup -q -n ibus-skk-1.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572892155
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1572892155
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ibus-skk
cp %{_builddir}/ibus-skk-1.4.3/COPYING %{buildroot}/usr/share/package-licenses/ibus-skk/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
%make_install
%find_lang ibus-skk

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/applications/ibus-setup-skk.desktop
/usr/share/ibus-skk/icons/ibus-skk.svg
/usr/share/ibus-skk/setup/ibus-skk-preferences.ui
/usr/share/ibus/component/skk.xml

%files libexec
%defattr(-,root,root,-)
/usr/libexec/ibus-engine-skk
/usr/libexec/ibus-setup-skk

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ibus-skk/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files locales -f ibus-skk.lang
%defattr(-,root,root,-)

